{{ config(materialized='view') }}

select
    repo_id,
    full_name,
    owner,
    name,
    html_url,
    description,
    primary_language,
    is_popular_language,
    popular_language_source,
    popular_language_source_url,
    stars_count,
    forks_count,
    watchers_count,
    open_issues_count,
    closed_issues_count,
    total_issues_count,
    closed_issues_ratio,
    accepted_pull_requests,
    releases_count,
    created_at,
    updated_at,
    pushed_at,
    age_days,
    days_since_last_update,
    archived,
    disabled,
    is_fork,
    default_branch,
    license_key,
    license_name,
    collected_at
from lab01_repos_populares
